// Blog listing seed data (PRD §7.7a: 10 launch titles, teaser/lorem bodies).
//
// Titles are verbatim from the source doc
// (758ab571-OOCWebsiteContentConsolidated.pdf, "Blog — launch article titles").
// BACKEND TODO: the source supplies titles only. Teasers and dates below are
// temporary editorial content and must be replaced by CMS records.

export type BlogPost = {
  slug: string;
  title: string;
  teaser: string;
  date: string;
  author: string;
  // Optional cover art. Left undefined until a file exists in
  // public/images/blog/; the ImageSlot renders a labelled placeholder meanwhile.
  image?: { src: string; alt: string };
};

const titles = [
  'Why "Great Culture" Claims No Longer Work — and What Does',
  "The Real Cost of Attrition — and the Culture Levers That Reduce It",
  "Silver, Gold, Platinum, Diamond: How to Read an OOC Certification Level",
  "Ten Questions to Ask in an Interview That Reveal Real Culture",
  "Inside a Multi-Stakeholder Assessment: Why One Voice Is Never Enough",
  "Employer Brand on a Mid-Market Budget: What Actually Moves the Needle",
  "What HR Leaders Get Wrong About Engagement Surveys",
  "The Job Seeker's Guide to Verifying an Employer Before You Sign",
  "Why Workplace Quality Belongs on the Board Agenda",
  "From Application to Certification: What the OOC Journey Really Involves",
];

const slugify = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

const publicationDates = ["12 Aug 2026", "28 Jul 2026", "09 Jul 2026", "24 Jun 2026", "05 Jun 2026"];

// Cover art, keyed by slug. Generated by scripts/generate-blog-art.mjs — abstract
// diagrams of each article's argument, not photography (see uiux.md). One file
// serves the listing thumbnail, the article hero and the homepage insight card.
// The alt text describes the concept, since that is what the image carries.
const art: Record<string, string> = {
  "why-great-culture-claims-no-longer-work-and-what-does":
    "An unevidenced claim shown as a broken dashed circle beside a verified one marked with a tick",
  "the-real-cost-of-attrition-and-the-culture-levers-that-reduce-it":
    "Declining bars representing attrition, with an upward lever arresting the fall",
  "silver-gold-platinum-diamond-how-to-read-an-ooc-certification-level":
    "Four ascending blocks representing the Silver, Gold, Platinum and Diamond levels",
  "ten-questions-to-ask-in-an-interview-that-reveal-real-culture":
    "Ten circles representing interview questions, one highlighted as the revealing one",
  "inside-a-multi-stakeholder-assessment-why-one-voice-is-never-enough":
    "Four differently coloured stakeholder nodes converging on a single central reading",
  "employer-brand-on-a-mid-market-budget-what-actually-moves-the-needle":
    "A gauge with its needle moved into the upper range",
  "what-hr-leaders-get-wrong-about-engagement-surveys":
    "A flat run of survey scores with one point breaking sharply upward",
  "the-job-seeker-s-guide-to-verifying-an-employer-before-you-sign":
    "A magnifying glass over a tick, beside a sealed certification mark",
  "why-workplace-quality-belongs-on-the-board-agenda":
    "An agenda where one line is raised and highlighted above the others",
  "from-application-to-certification-what-the-ooc-journey-really-involves":
    "Four milestones along a path, ending in a sealed certification mark",
};

export const blogPosts: BlogPost[] = titles.map((title, index) => {
  const slug = slugify(title);
  return {
    slug,
    title,
    teaser: `A practical introduction to ${title.toLowerCase()}.`,
    date: publicationDates[index % publicationDates.length],
    author: "Organisation of Choice Team",
    image: art[slug] ? { src: `/images/blog/${slug}.png`, alt: art[slug] } : undefined,
  };
});
